apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: test
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: benchmark-envoy
        image: benchmark-envoy/benchmark-envoy:latest
        imagePullPolicy: IfNotPresent
        args:
        - client
        - --addr
        - server.test.svc.cluster.local:80
        - --uri
        - http://server.test.svc.cluster.local:80/
        - --rps
        - "${RPS}"
        - --batch-period
        - "${BATCH_PERIOD}"
        - --pool-size
        - "${POOL_SIZE}"
