apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: test
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: benchmark-envoy
        image: benchmark-envoy/benchmark-envoy:latest
        imagePullPolicy: IfNotPresent
        args:
        - server
        - --addr
        - 0.0.0.0:80
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: test
spec:
  selector:
    app: server
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443